/**
 * HaloPSA AI Tool definitions for Vercel AI SDK.
 *
 * This module provides comprehensive AI-powered tools for interacting
 * with HaloPSA PSA/ITSM systems, covering:
 * - Ticket management (create, update, close, merge, bulk operations)
 * - Client/customer management
 * - Agent/technician management and workload
 * - Asset/device tracking
 * - Time tracking and billing
 * - Knowledge base articles and FAQs
 * - Contracts and SLAs
 * - Reports and dashboards
 */

import type { CoreTool } from 'ai';
import { createHaloContext, type HaloContext } from './context';
import { createTicketTools } from './tickets';
import { createClientTools } from './clients';
import { createAgentTools } from './agents';
import { createAssetTools } from './assets';
import { createBillingTools } from './billing';
import { createKnowledgeBaseTools } from './knowledgebase';
import { createContractTools } from './contracts';
import { createReportTools } from './reports';
import { createConfigurationTools } from './configuration';
import { createAttachmentTools } from './attachments';
import { createDashboardBuilderTools } from './dashboard-builder';
import { createDashboardValidatorTools } from './dashboard-validator';
import { createReportRepositoryTools } from './report-repository';
import { createWebResourceTools } from './web-resources';
import { createSchemaTools } from './schema';
import { createAutomationTools } from './automation';
import { createMemoryTools, getMemoryContextForUser } from './memory';
// Phase 1: Sales & Revenue
import { createOpportunityTools } from './opportunities';
import { createQuotationTools } from './quotations';
import { createSalesTools } from './sales';
// Phase 2: Operations & Scheduling
import { createAppointmentTools } from './appointments';
import { createTimesheetTools } from './timesheets';
import { createToDoTools } from './todos';
import { createCannedTextTools } from './canned-text';
// Phase 3: ITIL & Service Management
import { createApprovalTools } from './approvals';
import { createReleaseTools } from './releases';
import { createCABTools } from './cab';
import { createServiceCatalogTools } from './service-catalog';
// Phase 4: Productivity & Automation
import { createTicketRuleTools } from './ticket-rules';
import { createWebhookTools } from './webhooks';
import { createSearchTools } from './search';
import { createAuditTools } from './audit';
import { createNotificationTools } from './notifications';
// Phase 5: Integrations & Webhooks
import { createIntegrationTools } from './integrations';
// Phase 6: Advanced Features
import { createAdvancedTools } from './advanced';

export { createHaloContext, type HaloContext } from './context';
export { createWebResourceTools } from './web-resources';
export { createSchemaTools } from './schema';
export { createAutomationTools } from './automation';
export { createMemoryTools, getMemoryContextForUser } from './memory';

/**
 * Create all HaloPSA tools for the AI agent.
 */
export function createHaloTools(ctx: HaloContext): Record<string, CoreTool> {
  return {
    ...createTicketTools(ctx),
    ...createClientTools(ctx),
    ...createAgentTools(ctx),
    ...createAssetTools(ctx),
    ...createBillingTools(ctx),
    ...createKnowledgeBaseTools(ctx),
    ...createContractTools(ctx),
    ...createReportTools(ctx),
    ...createConfigurationTools(ctx),
    ...createAttachmentTools(ctx),
    ...createDashboardBuilderTools(ctx),
    ...createDashboardValidatorTools(ctx),
    ...createReportRepositoryTools(ctx),
    ...createSchemaTools(ctx),
    // Phase 1: Sales & Revenue
    ...createOpportunityTools(ctx),
    ...createQuotationTools(ctx),
    ...createSalesTools(ctx),
    // Phase 2: Operations & Scheduling
    ...createAppointmentTools(ctx),
    ...createTimesheetTools(ctx),
    ...createToDoTools(ctx),
    ...createCannedTextTools(ctx),
    // Phase 3: ITIL & Service Management
    ...createApprovalTools(ctx),
    ...createReleaseTools(ctx),
    ...createCABTools(ctx),
    ...createServiceCatalogTools(ctx),
    // Phase 4: Productivity & Automation
    ...createTicketRuleTools(ctx),
    ...createWebhookTools(ctx),
    ...createSearchTools(ctx),
    ...createAuditTools(ctx),
    ...createNotificationTools(ctx),
    // Phase 5: Integrations & Webhooks
    ...createIntegrationTools(ctx),
    // Phase 6: Advanced Features
    ...createAdvancedTools(ctx),
    // Web resource tools (no HaloContext required)
    ...createWebResourceTools(),
  };
}

/**
 * Create all HaloPSA tools from connection credentials.
 */
export function createHaloToolsFromConfig(config: {
  baseUrl: string;
  clientId: string;
  clientSecret: string;
  tenant?: string;
}): Record<string, CoreTool> {
  const ctx = createHaloContext(config);
  return createHaloTools(ctx);
}

/**
 * Get a list of all available tool names.
 */
export function getToolNames(): string[] {
  return [
    // Ticket tools
    'listTickets',
    'getTicket',
    'getTicketStats',
    'listSlaBreachedTickets',
    'listUnassignedTickets',
    'addTicketNote',
    'createTicket',
    'updateTicket',
    'assignTicket',
    'closeTicket',
    'changeTicketStatus',
    'changeTicketPriority',
    'bulkUpdateTickets',
    'bulkCloseTickets',
    'mergeTickets',
    'findDuplicateTickets',
    // Client tools
    'listClients',
    'getClient',
    'createClient',
    'updateClient',
    'getClientStats',
    'listSites',
    'getSite',
    'createSite',
    'updateSite',
    'listUsers',
    'getUser',
    'createUser',
    'updateUser',
    // Agent tools
    'listAgents',
    'getAgent',
    'getAgentWorkload',
    'listTeams',
    'getTeam',
    'getAgentAvailability',
    'listAgentCalendar',
    'getTeamAvailability',
    'createAgentCalendarEvent',
    'findAvailableAgents',
    // Asset tools
    'listAssets',
    'getAsset',
    'getAssetStats',
    'listWarrantyExpiring',
    'listWarrantyExpired',
    'createAsset',
    'updateAsset',
    'listAssetTypes',
    // Billing tools
    'listTimeEntries',
    'createTimeEntry',
    'getTimeSummary',
    'listInvoices',
    'getInvoice',
    'createInvoice',
    'createInvoiceFromTime',
    'sendInvoice',
    'markInvoicePaid',
    'getInvoiceSummary',
    'listProjects',
    'getProject',
    'createProject',
    'updateProject',
    // Knowledge base tools
    'listKbArticles',
    'getKbArticle',
    'searchKbArticles',
    'getKbSuggestions',
    'createKbArticle',
    'updateKbArticle',
    'getKbStats',
    'listFaqs',
    'createFaq',
    // Contract tools
    'listContracts',
    'getContract',
    'createContract',
    'updateContract',
    'renewContract',
    'getExpiringContracts',
    'getContractSummary',
    'listSlas',
    'getSla',
    'createSla',
    'createSlaTarget',
    'listRecurringServices',
    'createRecurringService',
    // Report tools
    'listReports',
    'searchReports',
    'getReport',
    'runReport',
    'exportReport',
    'createReport',
    'updateReport',
    'deleteReport',
    'cloneReport',
    'previewReportSql',
    'getReportColumns',
    'runSavedReport',
    'listScheduledReports',
    'createScheduledReport',
    // Dashboard tools
    'listDashboards',
    'getDashboard',
    'createDashboard',
    'updateDashboard',
    'deleteDashboard',
    'cloneDashboard',
    'shareDashboard',
    'addDashboardWidget',
    'listDashboardWidgets',
    'updateDashboardWidget',
    'removeDashboardWidget',
    // Chart tools
    'createChartReport',
    'getChartTypes',
    // Configuration tools
    'listCustomFields',
    'getCustomField',
    'createCustomField',
    'listTicketStatuses',
    'listTicketTypes',
    'listPriorities',
    'listCategories',
    'listWorkflows',
    'getWorkflow',
    'toggleWorkflow',
    'createWorkflow',
    'listEmailTemplates',
    'getEmailTemplate',
    'createEmailTemplate',
    'updateEmailTemplate',
    'listTicketTemplates',
    'getTicketTemplate',
    'createTicketFromTemplate',
    'createTicketTemplate',
    'listEscalationRules',
    'createEscalationRule',
    'listSystemSettings',
    'getSystemSetting',
    'updateSystemSetting',
    'getApiInfo',
    'getLookupValues',
    'getFieldInfo',
    'getSlaPolicies',
    // Attachment tools
    'listTicketAttachments',
    'getAttachment',
    'deleteAttachment',
    'copyAttachments',
    'uploadAttachment',
    // Dashboard builder tools
    'smartBuildDashboard',
    'smartBuildCustomDashboard',
    'suggestDashboardWidgets',
    'listDashboardTemplates',
    'findReportForWidget',
    // Dashboard validator tools
    'validateDashboard',
    'validateReport',
    'fixReport',
    'createValidatedReport',
    'listValidatedTemplates',
    'getValidatedSql',
    // Report repository tools
    'listRepositoryReports',
    'searchRepositoryReports',
    'getRepositoryReport',
    'importRepositoryReport',
    'getRepositoryCategories',
    'findAndImportReport',
    // Schema tools
    'getSqlSchemaContext',
    'getLookupTables',
    'getLookupValues',
    'getTicketStatuses',
    'getPriorities',
    'getCustomFields',
    'validateSqlQuery',
    // Web resource tools
    'fetchHaloPSADocs',
    'searchHaloPSAReddit',
    'fetchContext7Docs',
    'fetchWebPage',
    // Phase 1: Opportunity tools
    'listOpportunities',
    'getOpportunity',
    'createOpportunity',
    'updateOpportunity',
    'moveOpportunityStage',
    'closeOpportunity',
    'reopenOpportunity',
    'getPipelineStats',
    'listPipelineStages',
    // Phase 1: Quotation tools
    'listQuotations',
    'getQuotation',
    'createQuotation',
    'addQuotationLines',
    'sendQuotation',
    'acceptQuotation',
    'declineQuotation',
    'convertQuotationToInvoice',
    'convertQuotationToSalesOrder',
    'cloneQuotation',
    'generateQuotationPdf',
    // Phase 1: Sales order tools
    'listSalesOrders',
    'getSalesOrder',
    'createSalesOrder',
    'updateSalesOrderStatus',
    'convertSalesOrderToInvoice',
    // Phase 1: Supplier tools
    'listSuppliers',
    'getSupplier',
    'createSupplier',
    // Phase 1: Purchase order tools
    'listPurchaseOrders',
    'getPurchaseOrder',
    'createPurchaseOrder',
    'updatePurchaseOrderStatus',
    // Phase 1: Product tools
    'listProducts',
    'getProduct',
    'createProduct',
    'updateProductStock',
    'searchProducts',
    // Phase 2: Appointment tools
    'listAppointments',
    'getAppointment',
    'scheduleAppointment',
    'rescheduleAppointment',
    'cancelAppointment',
    'confirmAppointment',
    'completeAppointment',
    'getCalendarView',
    'getAgentAvailability',
    'getUpcomingAppointments',
    'getOverdueAppointments',
    // Phase 2: Timesheet tools
    'listTimesheets',
    'getTimesheet',
    'getCurrentTimesheet',
    'submitTimesheet',
    'approveTimesheet',
    'rejectTimesheet',
    'getPendingTimesheets',
    'listTimeEntries',
    'logTime',
    'startTimer',
    'stopTimer',
    'getTimeSummary',
    'listActivityTypes',
    // Phase 2: ToDo tools
    'listToDos',
    'getToDo',
    'createToDo',
    'startToDo',
    'completeToDo',
    'deferToDo',
    'cancelToDo',
    'reassignToDo',
    'setToDoPriority',
    'getDueTodayToDos',
    'getOverdueToDos',
    'getUpcomingToDos',
    'getToDoSummary',
    'listToDoGroups',
    'createToDoGroup',
    // Phase 2: Canned Text tools
    'listCannedTexts',
    'getCannedText',
    'getAvailableCannedTexts',
    'searchCannedTexts',
    'findCannedTextByShortcut',
    'createCannedText',
    'expandCannedText',
    'expandShortcut',
    'getMostUsedCannedTexts',
    'getRecentlyUsedCannedTexts',
    'getAvailableVariables',
    'validateCannedTextVariables',
    'listCannedTextCategories',
    'getCannedTextCategoryTree',
    'createCannedTextCategory',
    // Phase 3: Approval Process tools
    'listApprovalProcesses',
    'getApprovalProcess',
    'createApprovalProcess',
    'addApprovalRule',
    'listApprovalRules',
    'listTicketApprovals',
    'getPendingApprovals',
    'getTicketApprovals',
    'requestApproval',
    'approveTicket',
    'rejectTicket',
    'delegateApproval',
    'getApprovalStats',
    'getExpiredApprovals',
    // Phase 3: Release Management tools
    'listReleases',
    'getRelease',
    'createRelease',
    'updateReleaseStatus',
    'advanceReleaseStage',
    'setCABApproval',
    'addTicketsToRelease',
    'removeTicketsFromRelease',
    'getReleasesRequiringCAB',
    'getHighRiskReleases',
    'getReleaseCalendar',
    'searchReleases',
    'listReleaseTypes',
    'listReleasePipelines',
    'getPipelineWithStages',
    'createReleasePipeline',
    'listPipelineStages',
    // Phase 3: CAB tools
    'listCABs',
    'getCAB',
    'createCAB',
    'setCABChair',
    'listCABMembers',
    'addCABMember',
    'removeCABMember',
    'listCABRoles',
    'listCABMeetings',
    'getUpcomingCABMeetings',
    'getCABMeetingDetails',
    'scheduleCABMeeting',
    'startCABMeeting',
    'endCABMeeting',
    'cancelCABMeeting',
    'listReviewItems',
    'getPendingReviewItems',
    'addItemForReview',
    'recordCABDecision',
    'approveReviewItem',
    'rejectReviewItem',
    'deferReviewItem',
    'requestMoreInfo',
    'updateReviewItemAssessment',
    // Phase 3: Service Catalog tools
    'listServices',
    'getService',
    'getServicesWithIssues',
    'getCriticalServices',
    'createService',
    'updateServiceStatus',
    'searchServices',
    'listServiceCategories',
    'getServiceCategoryTree',
    'getServiceStatusHistory',
    'recordServiceStatusChange',
    'getRecentStatusChanges',
    'getServiceAvailability',
    'getServicesNotMeetingSLA',
    'listScheduledMaintenance',
    'getUpcomingMaintenance',
    'getCurrentMaintenance',
    'scheduleMaintenance',
    'startMaintenance',
    'completeMaintenance',
    'cancelMaintenance',
    'listServiceSubscribers',
    'subscribeToService',
    'unsubscribeFromService',
    // Phase 4: Ticket Rules tools
    'listTicketRules',
    'getTicketRule',
    'createTicketRule',
    'enableTicketRule',
    'disableTicketRule',
    'cloneTicketRule',
    'testTicketRule',
    'deleteTicketRule',
    'listRuleExecutionLogs',
    'getAvailableRuleFields',
    'getAvailableRuleActions',
    // Phase 4: Webhook tools
    'listWebhooks',
    'getWebhook',
    'createWebhook',
    'enableWebhook',
    'disableWebhook',
    'testWebhook',
    'deleteWebhook',
    'listWebhookEvents',
    'retryWebhookEvent',
    'listIncomingWebhooks',
    'getIncomingWebhook',
    'createIncomingWebhook',
    'enableIncomingWebhook',
    'disableIncomingWebhook',
    'regenerateIncomingWebhookToken',
    'listIncomingWebhookEvents',
    'getWebhookEventTypes',
    // Phase 4: Search tools
    'globalSearch',
    'quickSearch',
    'searchTickets',
    'searchClients',
    'searchAssets',
    'searchKnowledgeBase',
    'getSearchSuggestions',
    'listSavedSearches',
    'getSavedSearch',
    'executeSavedSearch',
    'createSavedSearch',
    'deleteSavedSearch',
    'listRecentSearches',
    'clearRecentSearches',
    'getSearchableEntityTypes',
    // Phase 4: Audit tools
    'listAuditLogs',
    'getAuditLog',
    'getAuditSummary',
    'searchAuditLogs',
    'getEntityAuditLogs',
    'getEntityHistory',
    'getTicketHistory',
    'compareEntityVersions',
    'listSecurityEvents',
    'getCriticalSecurityEvents',
    'resolveSecurityEvent',
    'getFailedLoginAttempts',
    'listAuditPolicies',
    // Phase 4: Notification tools
    'listNotifications',
    'getNotification',
    'getUnreadNotifications',
    'getUnreadCount',
    'sendNotification',
    'sendBulkNotifications',
    'markNotificationAsRead',
    'markAllNotificationsAsRead',
    'archiveNotification',
    'deleteNotification',
    'listNotificationTemplates',
    'getNotificationTemplate',
    'createNotificationTemplate',
    'enableNotificationTemplate',
    'disableNotificationTemplate',
    'previewNotificationTemplate',
    'getNotificationPreferences',
    'enableNotificationChannel',
    'disableNotificationChannel',
    'muteNotifications',
    'unmuteNotifications',
    'listNotificationSubscriptions',
    'subscribeToEntity',
    'subscribeToTicket',
    'subscribeToClient',
    'unsubscribeFromEntity',
    'getNotificationStats',
    // Phase 5: Integration tools
    'listIntegrations',
    'getIntegration',
    'getIntegrationByType',
    'createIntegration',
    'enableIntegration',
    'disableIntegration',
    'testIntegrationConnection',
    'deleteIntegration',
    'getAvailableIntegrationTypes',
    'listIntegrationMappings',
    'createIntegrationMapping',
    'deleteIntegrationMapping',
    'getAvailableMappingFields',
    'triggerSync',
    'getSyncStatus',
    'cancelSync',
    'getSyncHistory',
    'retryFailedRecords',
    'listIntegrationLogs',
    'getIntegrationErrors',
    'clearIntegrationLogs',
    'listExternalEntities',
    'lookupExternalEntity',
    'linkExternalEntity',
    'unlinkExternalEntity',
    'getAzureADConfig',
    'syncAzureADUsers',
    'syncAzureADGroups',
    'previewAzureADUsers',
    'getIntuneConfig',
    'syncIntuneDevices',
    'previewIntuneDevices',
    'getSlackConfig',
    'getSlackChannels',
    'sendSlackTestMessage',
    'getTeamsConfig',
    'getTeamsChannels',
    'sendTeamsTestMessage',
    'getNinjaRMMConfig',
    'syncNinjaRMMDevices',
    'syncNinjaRMMAlerts',
    'getNinjaRMMPendingAlerts',
    'getDattoConfig',
    'syncDattoDevices',
    'getDattoPendingAlerts',
    // Phase 6: Advanced Features
    // Currency tools
    'listCurrencies',
    'getCurrency',
    'getDefaultCurrency',
    // Tax tools
    'listTaxRates',
    'getTaxRate',
    'listTaxRules',
    'getApplicableTaxRule',
    // Holiday tools
    'listHolidays',
    'getHoliday',
    'getUpcomingHolidays',
    // Cost Centre tools
    'listCostCentres',
    'getCostCentre',
    'getCostCentreStats',
    // Budget Type tools
    'listBudgetTypes',
    'getBudgetType',
    // Qualification tools
    'listQualifications',
    'getQualification',
    'createQualification',
    'listAgentQualifications',
    'assignQualification',
    // Roadmap tools
    'listRoadmaps',
    'getRoadmap',
    'createRoadmap',
    'addRoadmapItem',
    // Password Field tools
    'listPasswordFields',
    'getPasswordValue',
    'setPasswordValue',
    // Bookmark tools
    'listBookmarks',
    'createBookmark',
    'deleteBookmark',
    // Mail Campaign tools
    'listMailCampaigns',
    'getMailCampaign',
    'createMailCampaign',
    'sendMailCampaign',
    'getMailCampaignStats',
    // Document Creation tools
    'listDocumentTemplates',
    'generateDocument',
    'getGeneratedDocuments',
    // PDF Template tools
    'listPdfTemplates',
    'getPdfTemplate',
    'generatePdf',
    // External Link tools
    'listExternalLinks',
    'createExternalLink',
    // Popup Note tools
    'listPopupNotes',
    'getPopupNote',
    'createPopupNote',
    'dismissPopupNote',
  ];
}

/**
 * Get tool categories for documentation.
 */
export const toolCategories = {
  tickets: [
    'listTickets',
    'getTicket',
    'getTicketStats',
    'listSlaBreachedTickets',
    'listUnassignedTickets',
    'addTicketNote',
    'createTicket',
    'updateTicket',
    'assignTicket',
    'closeTicket',
    'changeTicketStatus',
    'changeTicketPriority',
    'bulkUpdateTickets',
    'bulkCloseTickets',
    'mergeTickets',
    'findDuplicateTickets',
  ],
  clients: [
    'listClients',
    'getClient',
    'createClient',
    'updateClient',
    'getClientStats',
    'listSites',
    'getSite',
    'createSite',
    'updateSite',
    'listUsers',
    'getUser',
    'createUser',
    'updateUser',
  ],
  agents: [
    'listAgents',
    'getAgent',
    'getAgentWorkload',
    'listTeams',
    'getTeam',
    'getAgentAvailability',
    'listAgentCalendar',
    'getTeamAvailability',
    'createAgentCalendarEvent',
    'findAvailableAgents',
  ],
  assets: [
    'listAssets',
    'getAsset',
    'getAssetStats',
    'listWarrantyExpiring',
    'listWarrantyExpired',
    'createAsset',
    'updateAsset',
    'listAssetTypes',
  ],
  billing: [
    'listTimeEntries',
    'createTimeEntry',
    'getTimeSummary',
    'listInvoices',
    'getInvoice',
    'createInvoice',
    'createInvoiceFromTime',
    'sendInvoice',
    'markInvoicePaid',
    'getInvoiceSummary',
    'listProjects',
    'getProject',
    'createProject',
    'updateProject',
  ],
  knowledgeBase: [
    'listKbArticles',
    'getKbArticle',
    'searchKbArticles',
    'getKbSuggestions',
    'createKbArticle',
    'updateKbArticle',
    'getKbStats',
    'listFaqs',
    'createFaq',
  ],
  contracts: [
    'listContracts',
    'getContract',
    'createContract',
    'updateContract',
    'renewContract',
    'getExpiringContracts',
    'getContractSummary',
    'listSlas',
    'getSla',
    'createSla',
    'createSlaTarget',
    'listRecurringServices',
    'createRecurringService',
  ],
  reports: [
    'listReports',
    'searchReports',
    'getReport',
    'runReport',
    'exportReport',
    'createReport',
    'updateReport',
    'deleteReport',
    'cloneReport',
    'previewReportSql',
    'getReportColumns',
    'runSavedReport',
    'listScheduledReports',
    'createScheduledReport',
    // Dashboard operations
    'listDashboards',
    'getDashboard',
    'createDashboard',
    'updateDashboard',
    'deleteDashboard',
    'cloneDashboard',
    'shareDashboard',
    'addDashboardWidget',
    'listDashboardWidgets',
    'updateDashboardWidget',
    'removeDashboardWidget',
    // Chart configuration
    'createChartReport',
    'getChartTypes',
    // Smart dashboard builder
    'smartBuildDashboard',
    'smartBuildCustomDashboard',
    'suggestDashboardWidgets',
    'listDashboardTemplates',
    'findReportForWidget',
    // Dashboard validation
    'validateDashboard',
    'validateReport',
    'fixReport',
    'createValidatedReport',
    'listValidatedTemplates',
    'getValidatedSql',
    // Report repository
    'listRepositoryReports',
    'searchRepositoryReports',
    'getRepositoryReport',
    'importRepositoryReport',
    'getRepositoryCategories',
    'findAndImportReport',
  ],
  configuration: [
    'listCustomFields',
    'getCustomField',
    'createCustomField',
    'listTicketStatuses',
    'listTicketTypes',
    'listPriorities',
    'listCategories',
    'listWorkflows',
    'getWorkflow',
    'toggleWorkflow',
    'createWorkflow',
    'listEmailTemplates',
    'getEmailTemplate',
    'createEmailTemplate',
    'updateEmailTemplate',
    'listTicketTemplates',
    'getTicketTemplate',
    'createTicketFromTemplate',
    'createTicketTemplate',
    'listEscalationRules',
    'createEscalationRule',
    'listSystemSettings',
    'getSystemSetting',
    'updateSystemSetting',
    'getApiInfo',
    'getLookupValues',
    'getFieldInfo',
    'getSlaPolicies',
  ],
  attachments: [
    'listTicketAttachments',
    'getAttachment',
    'deleteAttachment',
    'copyAttachments',
    'uploadAttachment',
  ],
  schema: [
    'getSqlSchemaContext',
    'getLookupTables',
    'getLookupValues',
    'getTicketStatuses',
    'getPriorities',
    'getCustomFields',
    'validateSqlQuery',
  ],
  webResources: [
    'fetchHaloPSADocs',
    'searchHaloPSAReddit',
    'fetchContext7Docs',
    'fetchWebPage',
  ],
  automation: [
    'createAutomationRule',
    'listAutomationRules',
    'toggleAutomationRule',
    'deleteAutomationRule',
    'suggestAutomationRules',
  ],
  memory: [
    'saveToNotebook',
    'searchNotebook',
    'getNotebookEntry',
    'rememberContext',
    'recallContext',
    'getRecentContext',
    'deleteNotebookEntry',
    'toggleNotebookPin',
  ],
  // Phase 1: Sales & Revenue
  opportunities: [
    'listOpportunities',
    'getOpportunity',
    'createOpportunity',
    'updateOpportunity',
    'moveOpportunityStage',
    'closeOpportunity',
    'reopenOpportunity',
    'getPipelineStats',
    'listPipelineStages',
  ],
  quotations: [
    'listQuotations',
    'getQuotation',
    'createQuotation',
    'addQuotationLines',
    'sendQuotation',
    'acceptQuotation',
    'declineQuotation',
    'convertQuotationToInvoice',
    'convertQuotationToSalesOrder',
    'cloneQuotation',
    'generateQuotationPdf',
  ],
  salesOrders: [
    'listSalesOrders',
    'getSalesOrder',
    'createSalesOrder',
    'updateSalesOrderStatus',
    'convertSalesOrderToInvoice',
  ],
  suppliers: [
    'listSuppliers',
    'getSupplier',
    'createSupplier',
  ],
  purchaseOrders: [
    'listPurchaseOrders',
    'getPurchaseOrder',
    'createPurchaseOrder',
    'updatePurchaseOrderStatus',
  ],
  products: [
    'listProducts',
    'getProduct',
    'createProduct',
    'updateProductStock',
    'searchProducts',
  ],
  // Phase 2: Operations & Scheduling
  appointments: [
    'listAppointments',
    'getAppointment',
    'scheduleAppointment',
    'rescheduleAppointment',
    'cancelAppointment',
    'confirmAppointment',
    'completeAppointment',
    'getCalendarView',
    'getAgentAvailability',
    'getUpcomingAppointments',
    'getOverdueAppointments',
  ],
  timesheets: [
    'listTimesheets',
    'getTimesheet',
    'getCurrentTimesheet',
    'submitTimesheet',
    'approveTimesheet',
    'rejectTimesheet',
    'getPendingTimesheets',
    'listTimeEntries',
    'logTime',
    'startTimer',
    'stopTimer',
    'getTimeSummary',
    'listActivityTypes',
  ],
  todos: [
    'listToDos',
    'getToDo',
    'createToDo',
    'startToDo',
    'completeToDo',
    'deferToDo',
    'cancelToDo',
    'reassignToDo',
    'setToDoPriority',
    'getDueTodayToDos',
    'getOverdueToDos',
    'getUpcomingToDos',
    'getToDoSummary',
    'listToDoGroups',
    'createToDoGroup',
  ],
  cannedTexts: [
    'listCannedTexts',
    'getCannedText',
    'getAvailableCannedTexts',
    'searchCannedTexts',
    'findCannedTextByShortcut',
    'createCannedText',
    'expandCannedText',
    'expandShortcut',
    'getMostUsedCannedTexts',
    'getRecentlyUsedCannedTexts',
    'getAvailableVariables',
    'validateCannedTextVariables',
    'listCannedTextCategories',
    'getCannedTextCategoryTree',
    'createCannedTextCategory',
  ],
  // Phase 3: ITIL & Service Management
  approvals: [
    'listApprovalProcesses',
    'getApprovalProcess',
    'createApprovalProcess',
    'addApprovalRule',
    'listApprovalRules',
    'listTicketApprovals',
    'getPendingApprovals',
    'getTicketApprovals',
    'requestApproval',
    'approveTicket',
    'rejectTicket',
    'delegateApproval',
    'getApprovalStats',
    'getExpiredApprovals',
  ],
  releases: [
    'listReleases',
    'getRelease',
    'createRelease',
    'updateReleaseStatus',
    'advanceReleaseStage',
    'setCABApproval',
    'addTicketsToRelease',
    'removeTicketsFromRelease',
    'getReleasesRequiringCAB',
    'getHighRiskReleases',
    'getReleaseCalendar',
    'searchReleases',
    'listReleaseTypes',
    'listReleasePipelines',
    'getPipelineWithStages',
    'createReleasePipeline',
    'listPipelineStages',
  ],
  cab: [
    'listCABs',
    'getCAB',
    'createCAB',
    'setCABChair',
    'listCABMembers',
    'addCABMember',
    'removeCABMember',
    'listCABRoles',
    'listCABMeetings',
    'getUpcomingCABMeetings',
    'getCABMeetingDetails',
    'scheduleCABMeeting',
    'startCABMeeting',
    'endCABMeeting',
    'cancelCABMeeting',
    'listReviewItems',
    'getPendingReviewItems',
    'addItemForReview',
    'recordCABDecision',
    'approveReviewItem',
    'rejectReviewItem',
    'deferReviewItem',
    'requestMoreInfo',
    'updateReviewItemAssessment',
  ],
  serviceCatalog: [
    'listServices',
    'getService',
    'getServicesWithIssues',
    'getCriticalServices',
    'createService',
    'updateServiceStatus',
    'searchServices',
    'listServiceCategories',
    'getServiceCategoryTree',
    'getServiceStatusHistory',
    'recordServiceStatusChange',
    'getRecentStatusChanges',
    'getServiceAvailability',
    'getServicesNotMeetingSLA',
    'listScheduledMaintenance',
    'getUpcomingMaintenance',
    'getCurrentMaintenance',
    'scheduleMaintenance',
    'startMaintenance',
    'completeMaintenance',
    'cancelMaintenance',
    'listServiceSubscribers',
    'subscribeToService',
    'unsubscribeFromService',
  ],
  // Phase 4: Productivity & Automation
  ticketRules: [
    'listTicketRules',
    'getTicketRule',
    'createTicketRule',
    'enableTicketRule',
    'disableTicketRule',
    'cloneTicketRule',
    'testTicketRule',
    'deleteTicketRule',
    'listRuleExecutionLogs',
    'getAvailableRuleFields',
    'getAvailableRuleActions',
  ],
  webhooks: [
    'listWebhooks',
    'getWebhook',
    'createWebhook',
    'enableWebhook',
    'disableWebhook',
    'testWebhook',
    'deleteWebhook',
    'listWebhookEvents',
    'retryWebhookEvent',
    'listIncomingWebhooks',
    'getIncomingWebhook',
    'createIncomingWebhook',
    'enableIncomingWebhook',
    'disableIncomingWebhook',
    'regenerateIncomingWebhookToken',
    'listIncomingWebhookEvents',
    'getWebhookEventTypes',
  ],
  globalSearch: [
    'globalSearch',
    'quickSearch',
    'searchTickets',
    'searchClients',
    'searchAssets',
    'searchKnowledgeBase',
    'getSearchSuggestions',
    'listSavedSearches',
    'getSavedSearch',
    'executeSavedSearch',
    'createSavedSearch',
    'deleteSavedSearch',
    'listRecentSearches',
    'clearRecentSearches',
    'getSearchableEntityTypes',
  ],
  audit: [
    'listAuditLogs',
    'getAuditLog',
    'getAuditSummary',
    'searchAuditLogs',
    'getEntityAuditLogs',
    'getEntityHistory',
    'getTicketHistory',
    'compareEntityVersions',
    'listSecurityEvents',
    'getCriticalSecurityEvents',
    'resolveSecurityEvent',
    'getFailedLoginAttempts',
    'listAuditPolicies',
  ],
  notifications: [
    'listNotifications',
    'getNotification',
    'getUnreadNotifications',
    'getUnreadCount',
    'sendNotification',
    'sendBulkNotifications',
    'markNotificationAsRead',
    'markAllNotificationsAsRead',
    'archiveNotification',
    'deleteNotification',
    'listNotificationTemplates',
    'getNotificationTemplate',
    'createNotificationTemplate',
    'enableNotificationTemplate',
    'disableNotificationTemplate',
    'previewNotificationTemplate',
    'getNotificationPreferences',
    'enableNotificationChannel',
    'disableNotificationChannel',
    'muteNotifications',
    'unmuteNotifications',
    'listNotificationSubscriptions',
    'subscribeToEntity',
    'subscribeToTicket',
    'subscribeToClient',
    'unsubscribeFromEntity',
    'getNotificationStats',
  ],
  // Phase 5: Integrations & Webhooks
  integrations: [
    'listIntegrations',
    'getIntegration',
    'getIntegrationByType',
    'createIntegration',
    'enableIntegration',
    'disableIntegration',
    'testIntegrationConnection',
    'deleteIntegration',
    'getAvailableIntegrationTypes',
    'listIntegrationMappings',
    'createIntegrationMapping',
    'deleteIntegrationMapping',
    'getAvailableMappingFields',
    'triggerSync',
    'getSyncStatus',
    'cancelSync',
    'getSyncHistory',
    'retryFailedRecords',
    'listIntegrationLogs',
    'getIntegrationErrors',
    'clearIntegrationLogs',
    'listExternalEntities',
    'lookupExternalEntity',
    'linkExternalEntity',
    'unlinkExternalEntity',
    'getAzureADConfig',
    'syncAzureADUsers',
    'syncAzureADGroups',
    'previewAzureADUsers',
    'getIntuneConfig',
    'syncIntuneDevices',
    'previewIntuneDevices',
    'getSlackConfig',
    'getSlackChannels',
    'sendSlackTestMessage',
    'getTeamsConfig',
    'getTeamsChannels',
    'sendTeamsTestMessage',
    'getNinjaRMMConfig',
    'syncNinjaRMMDevices',
    'syncNinjaRMMAlerts',
    'getNinjaRMMPendingAlerts',
    'getDattoConfig',
    'syncDattoDevices',
    'getDattoPendingAlerts',
  ],
  // Phase 6: Advanced Features
  currencies: [
    'listCurrencies',
    'getCurrency',
    'getDefaultCurrency',
  ],
  taxes: [
    'listTaxRates',
    'getTaxRate',
    'listTaxRules',
    'getApplicableTaxRule',
  ],
  holidays: [
    'listHolidays',
    'getHoliday',
    'getUpcomingHolidays',
  ],
  costCentres: [
    'listCostCentres',
    'getCostCentre',
    'getCostCentreStats',
  ],
  budgetTypes: [
    'listBudgetTypes',
    'getBudgetType',
  ],
  qualifications: [
    'listQualifications',
    'getQualification',
    'createQualification',
    'listAgentQualifications',
    'assignQualification',
  ],
  roadmaps: [
    'listRoadmaps',
    'getRoadmap',
    'createRoadmap',
    'addRoadmapItem',
  ],
  passwordFields: [
    'listPasswordFields',
    'getPasswordValue',
    'setPasswordValue',
  ],
  bookmarks: [
    'listBookmarks',
    'createBookmark',
    'deleteBookmark',
  ],
  mailCampaigns: [
    'listMailCampaigns',
    'getMailCampaign',
    'createMailCampaign',
    'sendMailCampaign',
    'getMailCampaignStats',
  ],
  documentCreation: [
    'listDocumentTemplates',
    'generateDocument',
    'getGeneratedDocuments',
  ],
  pdfTemplates: [
    'listPdfTemplates',
    'getPdfTemplate',
    'generatePdf',
  ],
  externalLinks: [
    'listExternalLinks',
    'createExternalLink',
  ],
  popupNotes: [
    'listPopupNotes',
    'getPopupNote',
    'createPopupNote',
    'dismissPopupNote',
  ],
} as const;
